### ISSUE TITLE
Install/Uninstall crossplane deployment

### ISSUE THREAD

**Issue by jimmykarily** [SUSE/carrier#159]
This is the first step to get services on public cloud providers. 

Next step is #157

# Acceptance Criteria

- There should be a way to enable the broker functionality after installing Carrier
  In the future we may automate that. E.g. when the cluster is a public cloud one, we could automatically install all the crossplane components and enable this feature.  For now we can skip the auto-detection and enable the services feature manually. This is just to keep the needed changes small and split to multiple issues for easier management.

- The above should happen with a single command (in the same way `carrier install` works)
- There should be a way to disable this feature.
  When that happens the relevant components should be removed from the cluster. Any provisioned services should also be removed (a warning should probably be shown to the user).

**Comment by jimmykarily** [comment]
It turns out crossplane is not doing what we hoped it does. There are no real abstractions, at least nothing pre-made for us to use. The [composition concept](https://crossplane.io/docs/v1.0/introduction/composition.html) is there to allow some team to create the abstraction (called "CompositeXInstance") for the application developers to use. There are no publicly available Composites which we can use in Carrier.

If we were to create those abstractions ourselves (Carrier team), that means we need to write code (or yaml) to support each and every service we want to make available to our users. This is no different from using the upstream controller/crds (e.g. config connector from google or equivalent from Azure and others).

To sum it up, with crossplane:

- we don't get access to an arbitrary list of services provided by public cloud providers
- we don't get a generic way to provision services on different providers
- it's not easier in any way compared to using the upstream controllers/crds


With this in mind, we propose the following plan:

1. Do #160 first. This means we will be able to create "Services" in the same style as [cups](https://docs.run.pivotal.io/devguide/services/user-provided.html) in CloudFoundry. The process is a follows:
  - The user creates a service (e.g. using helm or crossplane or whatever they prefer).
  - The user creates the "Service" using carrier. This will create a secret and put the provided credentials in there (as it works with cf cups)
  - The user can now "bind" the service one or more applications. This will mount the above secret as a file or env var.

1. Use service catalog (instead of crossplane) and implement the local service feature
1. Add more service brokers to support (some) public cloud providers for as long as they maintain their brokers.

With step 1, we have a way for the user to bind service to the applications, even if they have to provision the services manually. This is already making Carrier useful.
With step 2, we support the local development flow.
With step 3, we support as many public cloud providers as possible. For the rest, the user will have to use the tooling from the cloud provider to manually provision services and bind them as described in step 1 above.

**Comment by satadruroy** [comment]
Thanks for looking into it @jimmykarily - it reinforces my doubts about why anyone would want to use something like crossplane as opposed to the provider specific operators if the cross-platform abstraction is too limited/hard to use. The composite construct seems hard to use.

As for our direction, I'd just point out the service brokers from the 3 big players are practically dead so I probably won't want us to to be tied too much into them. From what I've heard from PM on calls with public cloud team, the Azure PM felt OSBAPI did not meet their needs and they were going to focus all their efforts on the operators which seems to be what's happening now across all of the providers. Maybe letting the users "bring their own service" with a simple binding mechanism is good for now.

**Comment by satadruroy** [comment]
@jimmykarily @andreas-kupries I asked the question ^ on the crossplane slack channel and they are pointing me to https://crossplane.io/docs/v1.0/getting-started/compose-infrastructure.html as a pre-made composite example. Looks like this does the secret binding as well. Would this work for us?

**Comment by jimmykarily** [comment]
@satadruroy thank you for asking them for more information. We've seen that page and as you said, these are provider specific resources (so no abstraction). This is what they suggest you to do to get a `CloudSQLInstance` with Crossplane:

```
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: cloudsqlpostgresql
spec:
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: us-central1
    settings:
      tier: db-custom-1-3840
      dataDiskType: PD_SSD
      dataDiskSizeGb: 10
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cloudsqlpostgresql-conn
```

and this is what you need to do to achieve the same with Google config connector:

```
  apiVersion: sql.cnrm.cloud.google.com/v1beta1
  kind: SQLInstance
  metadata:
    name: sqlinstance-sample-postgreshighavailability
  spec:
    databaseVersion: POSTGRES_9_6
    region: us-central1
    settings:
      tier: db-custom-1-3840
      availabilityType: REGIONAL
```

(taken [from the docs](https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance#postgres_sql_instance_high_availability))

I can't see how crossplane makes it easier. The only was crossplane would make this easier would be if someone went into the trouble of creating a composite for postgres and then the user could use and almost identical yaml to provision a database in various cloud providers. But that's not what we need.
